In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("train.csv", index_col="Id")

In [3]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [4]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

In [5]:
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

In [6]:
X = data[features]
y = data['SalePrice']

In [7]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [8]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

In [10]:
X_train.shape

(1168, 7)

In [11]:
X_valid.shape

(292, 7)

In [12]:
data.shape

(1460, 80)

In [13]:
1168/1460

0.8

In [14]:
# training machine learning module

from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1, )

In [15]:
# fit training data model

dt_model.fit(X_train, y_train)


DecisionTreeRegressor(random_state=1)

In [16]:
y_predics = dt_model.predict(X_valid.head())

In [17]:
y_predics

array([335000., 140200., 119000., 207500., 112000.])

In [18]:
pd.DataFrame({'y': y_valid.head(), 'y_predics': y_predics})

y  y_predics
Id                    
530  200624   335000.0
492  133000   140200.0
460  110000   119000.0
280  192000   207500.0
656   88000   112000.0

In [19]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(X_train, y_train)


RandomForestRegressor(random_state=1)

In [20]:
rf_valid_preds = rf_model.predict(X_valid)

In [21]:
rf_valid_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [22]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [23]:
rf_model.predict([[1234, 2020, 800, 750, 4, 5, 9]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([164780.])